Hotels/urls.py
from django.urls import path
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView

app_name = "Hotels"
urlpatterns = [
    # 一覧画面
    path('',  ItemFilterView.as_view(), name='index'),
    # 詳細画面
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    # 登録画面
    path('create/', ItemCreateView.as_view(), name='create'),
    # 更新画面
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    # 削除画面
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
]

Practice3/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Hotels.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

Hotels/models.py
from django.db import models


class Item(models.Model):
    CONDITION_CHOICES = (
        (1, "ショッピング"),
        (2, "娯楽施設"),
        (3, "温泉"),
        (4, "日本文化体験"),
        (5, "食の名産"),
        (6, "テーマパーク"),
        (7, "景色")
    )
    FEE_CHOICES = (
        (1, "~1万円"),
        (2, "~2万円"),
        (3, "~3万円")
    )
    name = models.CharField(
        verbose_name='宿名',
        max_length=50,
        blank=True,
        null=True
    )
    stadium = models.CharField(
        verbose_name='会場',
        max_length=40,
        blank=True,
        null=True
    )
    condition = models.IntegerField(
        verbose_name='条件',
        choices=CONDITION_CHOICES,
        default=1,
        blank=True,
        null=True,
    )
    fee = models.IntegerField(
        verbose_name="料金",
        blank=True,
        null=True
    )
    fee_choices = models.IntegerField(
        verbose_name='料金幅',
        choices=FEE_CHOICES,
        default=1,
        blank=True,
        null=True,
    )
    area = models.CharField(
        verbose_name='エリア',
        max_length=20,
        blank=True,
        null=True
    )
    image = models.ImageField(
        verbose_name="写真",
        upload_to='media',
        blank=True,
        null=True)
    detail = models.TextField(
        verbose_name='詳細',
        blank=True,
        null=True)
    created_at = models.DateTimeField(
        verbose_name='登録日',
        auto_now_add=True
    )

    # 以下は管理サイト上の表示設定
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'アイテム'
        verbose_name_plural = 'アイテム'

Hotels/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('stadium', 'fee', 'condition')
        widgets = {
            'stadium': forms.TextInput(attrs={'placeholder': '記入例：Olympic Stadium'}),
            'fee': forms.SelectMultiple(choices=Item.FEE_CHOICES),
            'condition': forms.SelectMultiple(choices=Item.CONDITION_CHOICES)
        }

Hotels/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from .models import Item
from .filters import ItemFilter
from .forms import ItemForm


# Create your views here.
# 検索一覧画面
class ItemFilterView(LoginRequiredMixin, FilterView):
    model = Item
    filterset_class = ItemFilter
    # デフォルトの並び順を新しい順とする
    queryset = Item.objects.all().order_by('-created_at')

    # クエリ未指定の時に全件検索を行うために以下のオプションを指定（django-filter2.0以降）
    strict = False

    # 1ページあたりの表示件数
    paginate_by = 10

    # 検索条件をセッションに保存する or 呼び出す
    def get(self, request, **kwargs):
        if request.GET:
            request.session['query'] = request.GET
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]

        return super().get(request, **kwargs)


# 詳細画面
class ItemDetailView(LoginRequiredMixin, DetailView):
    model = Item


# 登録画面
class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')


# 更新画面
class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')


# 削除画面
class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    success_url = reverse_lazy('Hotels:index')

Hotels/templates/Hotels/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Suburb Hotel Finder</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="{% static "Hotels/css/Hotels.css" %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href={% url 'Hotels:index'%}>Suburb Hotel Finder</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false"
            aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'%}">管理サイト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:logout'%}">ログアウト</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    {% block content %}
    {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static "Hotels/js/plugins/responsive-paginate.js" %}"></script>
    <script src="{% static "Hotels/js/Hotels.js" %}"></script>
</body>

</html>

Hotels/templates/Hotels/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev ">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

Hotels/templates/Hotels/item_card.html
<div class="row">
    <div class="col-3">
        <p>宿名</p>
    </div>
    <div class="col-9">
        <p>{{ item.name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>平均料金</p>
    </div>
    <div class="col-9">
        <p>{{ item.get_fee_choices_display }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>イメージ</p>
    </div>
    <div class="col-9">
        <img src="{{ item.image }}"/>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>詳細</p>
    </div>
    <div class="col-9">
        <p>{{ item.detail|linebreaksbr }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>登録日</p>
    </div>
    <div class="col-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>

Hotels/templates/Hotels/item_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
<div class="container">
    <h2 class="text-center">データ削除</h2>
    <p>このデータを削除します。よろしいですか？</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'Hotels:index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
        {% include "./item_card.html" %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'Hotels:index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

Hotels/templates/Hotels/item_detail.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <h2 class="text-center">詳細表示</h2>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'Hotels:index' %}">戻る</a>
        </div>
    </div>
    <!--  -->
    {% include "./item_card.html" %}
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'Hotels:index' %}">戻る</a>
        </div>
    </div>
</div>
{% endblock %}

Hotels/templates/Hotels/item_filter.html
{% extends "./_base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">検索条件</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="filter" method="get">
                    <div class="modal-body">
                        {{filter.form|crispy}}
                    </div>
                </form>
                <div class="modal-footer">
                    <a class="btn btn-outline-secondary" data-dismiss="modal">戻る</a>
                    <button type="submit" class="btn btn-outline-secondary" form="filter">検索</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
            <div class="float-left">
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
            </div>
        </div>
    </div>

    <h5 class="text">検索条件を上のボタンから選択してください</h5>
    <hr>

    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                {% for item in item_list %}
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-3">
                            <p>宿:</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>ジャンル:</p>
                        </div>
                        <div class="col-9">
                            <p>{{item.get_condition_display}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                <a class="btn btn-outline-secondary " href="{% url 'Hotels:detail' item.pk %}">詳細</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                <li class="list-group-item">
                    対象のデータがありません
                </li>
                {% endfor %}
            </ul>
        <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                {% include "./_pagination.html" %}
                            </div>
                        </div>
                    </div>
        </div>
    </div>

</div>
{% endblock %}

Hotels/templates/Hotels/item_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.certifications.errors }}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center">データ入力</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'Hotels:index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="{% url 'Hotels:index' %}">保存</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" id="myform">
                {%crispy form%}
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'Hotels:index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="{% url 'Hotels:index' %}">保存</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}